//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_Adressverwaltung
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AddressEntities : DbContext
    {
        public DB_AddressEntities()
            : base("name=DB_AddressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anschrift> Anschrifts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Stadt> Stadts { get; set; }
    }
}
