//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_Adressverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stadt()
        {
            this.Anschrifts = new HashSet<Anschrift>();
        }
    
        public int StadtID { get; set; }
        public string StadtCode { get; set; }
        public string StadtName { get; set; }
        public string LandCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anschrift> Anschrifts { get; set; }
    }
}
